# Generated by Django 3.0.6 on 2020-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='address_line_one',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='address_line_two',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='city',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='nic',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='province',
            field=models.CharField(choices=[('cp', 'Central Province'), ('ep', 'Eastern Province'), ('np', 'Northern Province'), ('sp', 'Southern Province'), ('wp', 'Western Province'), ('nwp', 'North Western Province'), ('ncp', 'North Central Province'), ('up', 'Uva Province'), ('sgp', 'Sabaragamuwa Province')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='vehicle_reg',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='applied_date',
            field=models.DateField(auto_now=True),
        ),
    ]
